name: SBIR web product
# 設定當push，main節點的時候觸發此CI/CD流程
on:
  push:
    branches:
      - main
jobs:
  # 工作流程名稱可以自己取名
  build:
  # 設定runner
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.12.1]
        
    steps:
    # 取得程式碼
    - name: get code
      uses: actions/checkout@v3
    # 安裝node.js
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.1'
    # 設定快取
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
        node_modules
        ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    # 安裝npm
    - name: Install dependencies
      run: npm ci
    # build檔案
    - name: Build
      run: npm run build
  
  deploy:
    runs-on: self-hosted
    if: ${{ success() }}
    needs: build
  
    steps: 
    - name: Deploy-Product
      run: |
        cp -r -Force ${{ secrets.SrcPath }} ${{ secrets.SrcPath }}backup
        rm -r ${{ secrets.SrcPath }}
        mkdir ${{ secrets.SrcPath }}
        cp -r -Force dist/* ${{ secrets.SrcPath }}
